[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "6wphNBvMTUwuwgunq79J2o7ihJVdcXmDwzskN66x9GP3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/rahul703/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
