[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_jackpot = "DP1BGMQdhhTE6CehdvhgQTBZe8mtA4RvmcAg8DQ6oxkd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rahul703/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
